# Change these first
owner: starkaistatus # Your GitHub username
repo: Uptime # Your GitHub repository name

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# Add your sites here
sites:
  - name: Stark AI
    url: https://starkai.live
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Stark AI Beta
    url: https://beta.starkai.live
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: API Endpoint
    url: https://starkai.live/sydeny/chat/message/hi
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  favicon: https://graph.org/file/d544abfc59ac3a2028489.jpg
  baseUrl: /uptime
  theme: dark
  cname: status.starkai.live
  logoUrl: https://graph.org/file/d544abfc59ac3a2028489.jpg
  name: Stark AI Status
  introTitle: " "
  introMessage: " " 
  
  navbar:
    - title: Stark AI
      href: https://starkai.live
    - title: Stark AI Beta
      href: https://beta.starkai.live
    - title: Playground
      href: https://starkai.live/playground

i18n:
  footer: "©️ 2023 [Stark AI](https://starkai.live)"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#  up: "✅ Up"
#  degraded: "⚠️ Degraded"
#  down: "🚨 Down"
#  liveStatusHtmlComment: "<!--live status-->"
#  allSystemsOperational: "✅ All systems operational"
#  degradedPerformance: "⚠️ Degraded performance"
#  completeOutage: "🚨 Complete outage"
#  partialOutage: "🟧 Partial outage"  

commitMessages:
  commitAuthorName: "Stark AI"
  commitAuthorEmail: "support@starkai.live"

workflowSchedule:
  uptime: "*/2 * * * *"
